a = input('Ola, digite algo: ')
print('O tipo primitivo desse é: ', type(a))
print('So tem espoços? ', a.isspace())
print('É um numero? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alfanumerico? ', a.isalnum())
print('Está em maiusculo? ', a.isupper())
print('Está em minusculo? ', a.islower())
print('Está capitalizada? ', a.istitle())
